### ISSUE TITLE
Can't import the App

### ISSUE THREAD

**Issue by Roodmack** [misskristine94/NeumorphicUIKitDark#1]
Hi, 

First of all thank you sharing, 
i have an issue when i try to import the app
i try different way : Solution, App Package, Component
still get an error ! 

can you please check it, or release it in a unmanage solution 

Best regards,

**Comment by kristinekolodziejski** [comment]
Hi Roodmack,

Thank you very much!

This app is not in a solution - it's wrapped in an app package. To install it in your environment, you need to go to Apps

![image](https://user-images.githubusercontent.com/86930618/179360444-338db42a-25b2-404e-a645-090e225a0513.png)

Then click on 'Import Canvas App'

![image](https://user-images.githubusercontent.com/86930618/179360459-e3cab90d-145b-4589-ae00-e1f5495069c6.png)

Then click on Upload

![image](https://user-images.githubusercontent.com/86930618/179360474-1388c5f8-6211-4d53-9f4c-697e226145ca.png)

Give it a minute or two to process

![image](https://user-images.githubusercontent.com/86930618/179360497-ce1f9eb9-d7b3-47ec-8e69-590ed5c486cb.png)

And then click Import

![image](https://user-images.githubusercontent.com/86930618/179360506-3a6e5ff6-e270-4081-9c57-f1ff9c61b813.png)



Hope this helps - please let me know if you have any further issues, please include a screenshot too as it's always easier to troubleshoot that way :)

**Comment by Roodmack** [comment]
Thank you for your quick Answer,

here's a picture of the error

![Issue import](https://user-images.githubusercontent.com/96177590/179361288-b7afa53b-506b-4b22-8b93-4696dc8bdcb2.JPG)

it's still persist

**Comment by kristinekolodziejski** [comment]
@Roodmack  it looks like you downloaded the whole repo, not the file itself 😊

You need to go to this link - 

https://github.com/misskristine94/NeumorphicUIKitDark/blob/main/NeumorphicUIKit-Dark_20220713225054.zip

And click on download :) 

![image](https://user-images.githubusercontent.com/86930618/179361374-43b8bd42-5d74-49b6-91f4-d3f921ce3271.png)


Hope this works!

**Comment by Roodmack** [comment]
Got it ! 

it works ...😁😁😁😁😁

thank you


![image](https://user-images.githubusercontent.com/96177590/179361600-539bdc04-ba08-4f45-b13e-007f0bf1ec21.png)

**Comment by kristinekolodziejski** [comment]
Amazing!! I'm glad it works! Enjoy 😁
